app-misc/kclock: new package
gentoo/kde pull request #922
Opened 2023-04-26 14:59 UTC by CyberTailor

2023-05-25 20:33 UTC, a17r approved these changes
Minor nits as other two PRs.

Thanks for your work, looks solid. I'll try to get to build, install and check deps soon.

2023-05-26 20:50 UTC, a17r requested changes

2023-05-26 20:50 UTC, a17r commented on app-misc/kclock/kclock-23.04.49.9999.ebuild
> +	>=dev-qt/qtmultimedia-${QTMIN}:5
missing `qml` USEdep here

2023-05-26 20:50 UTC, a17r commented on app-misc/kclock/kclock-23.04.49.9999.ebuild
> +RDEPEND="${DEPEND}"
missing `RDEPEND=">=dev-qt/qtgraphicaleffects-${QTMIN}:5"`

2023-05-27 08:26 UTC, CyberTailor commented on app-misc/kclock/kclock-23.04.49.9999.ebuild
> +RDEPEND="${DEPEND}"
Fixed

2023-05-27 08:26 UTC, CyberTailor commented on app-misc/kclock/kclock-23.04.49.9999.ebuild
> +	>=dev-qt/qtmultimedia-${QTMIN}:5
Fixed

2023-05-27 09:42 UTC, a17r approved these changes

2023-05-27 15:57 UTC, closed without merging

2023-05-27 16:13 UTC, a17r commented
https://bugs.gentoo.org/907251